### Product index
GET http://localhost:3000/products.json

### Product create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test_name2",
  "price": "39",
  "image_url": "test_image_url",
  "description": "test_description"
}


### Product show
GET http://localhost:3000/products/1.json

### Product update
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "name": "shoebox!",
  "price": 42
}

### Product destroy
DELETE http://localhost:3000/products/6