@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4MzE0MDl9.XMgFjB8ky0pMSxFRZUgrv2Ca9wf2gILAEkQYCpA5o-o



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Admin Name",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}

# admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4MzE0MDl9.XMgFjB8ky0pMSxFRZUgrv2Ca9wf2gILAEkQYCpA5o-o

# first = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI4Mjk0ODh9.utzMkbRZC4tcfEPLKuFqB4F-Vdvva3hUYrzn5Lf-3DM

# second = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTI4Mjk3NDV9.i2pC8DzudclqZW8u6YFKxesXD4y4y6zpl99wI84AlPo

### Orders index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}


### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}

### Orders show
GET http://localhost:3000/orders/13.json
Authorization: Bearer {{jwt}}


### Product index
GET http://localhost:3000/products.json

### Product create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "product_test_name4",
  "price": 11,
  "description": "product_test_description",
  "supplier_id": 1
}


### Product show
GET http://localhost:3000/products/1.json

### Product update
PATCH http://localhost:3000/products/2.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Grogu!",
  "price": 21
}

### Product destroy
DELETE http://localhost:3000/products/2
Authorization: Bearer {{jwt}}


### Supplier index
GET http://localhost:3000/suppliers.json