@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTMwMDU3Mjd9.FpnRVfFR7Z1GRm1PTtcJbt6DqweXW57wBY4Kl6aPjSE



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Admin Name",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}

# admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTMwMDQ2MDN9.T4QpIuC4T3rFFGvTr0XUR_TdqcrtVwOQYtNXRX0FKEc

# first = 

# second = 

### Orders index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}


### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}

### Orders show
GET http://localhost:3000/orders/13.json
Authorization: Bearer {{jwt}}


### Product index
GET http://localhost:3000/products.json

### Product create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "product_test_name4",
  "price": 11,
  "description": "product_test_description",
  "supplier_id": 1
}


### Product show
GET http://localhost:3000/products/1.json

### Product update
PATCH http://localhost:3000/products/2.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Star Wars The Child Talking Plush Toy with Character Sounds and Accessories, The Mandalorian Toy",
  "price": 21
}

### Product destroy
DELETE http://localhost:3000/products/2
Authorization: Bearer {{jwt}}


### Supplier index
GET http://localhost:3000/suppliers.json



### CartedProduct index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}



### CartedProduct create
POST http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 3,
  "quantity": 3,
  "status": "purchased"
}